public with sharing class GithubUser {
    public class fullUser {
        public String login;	//octocat
        public Integer id;	//583231
        public String node_id;	//MDQ6VXNlcjU4MzIzMQ==
        public String avatar_url;	//https://avatars.githubusercontent.com/u/583231?v=4
        public String gravatar_id;	//
        public String url;	//https://api.github.com/users/octocat
        public String html_url;	//https://github.com/octocat
        public String followers_url;	//https://api.github.com/users/octocat/followers
        public String following_url;	//https://api.github.com/users/octocat/following{/other_user}
        public String gists_url;	//https://api.github.com/users/octocat/gists{/gist_id}
        public String starred_url;	//https://api.github.com/users/octocat/starred{/owner}{/repo}
        public String subscriptions_url;	//https://api.github.com/users/octocat/subscriptions
        public String organizations_url;	//https://api.github.com/users/octocat/orgs
        public String repos_url;	//https://api.github.com/users/octocat/repos
        public String events_url;	//https://api.github.com/users/octocat/events{/privacy}
        public String received_events_url;	//https://api.github.com/users/octocat/received_events
        public String type;	//User
        public boolean site_admin;
        public String name;	//The Octocat
        public String company;	//@github
        public String blog;	//https://github.blog
        public String location;	//San Francisco
        public String email;
        public boolean hireable;
        public string bio;
        public string twitter_username;
        public Integer public_repos;	//8
        public Integer public_gists;	//8
        public Integer followers;	//5547
        public Integer following;	//9
        public String created_at;	//2011-01-25T18:44:36Z
        public String updated_at;	//2022-03-22T14:07:15Z
    }

    public class halfUser{
        public String login;	//octocat
        public String html_url;	//https://github.com/octocat
        public String name;	//The Octocat
        public String avatar_url;	//https://avatars.githubusercontent.com/u/583231?v=4
    }
}
